//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Roop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Акт приемки.
    /// </summary>
    // *** Start programmer edit section *** (АктПриемки CustomAttributes)

    // *** End programmer edit section *** (АктПриемки CustomAttributes)
    [AutoAltered()]
    [Caption("Акт приемки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АктПриемкиE", new string[] {
            "ДатаПриемки as \'Дата приемки\'",
            "НомерАкта as \'Номер акта\'",
            "ФИО as \'ФИО\'",
            "Должность as \'Должность\'",
            "НомерТН as \'Номер ТН\'",
            "Поставщик as \'Поставщик\'",
            "НомерПозиции as \'Номер позиции\'",
            "Материал as \'Материал\'",
            "Колво as \'Колво\'"})]
    [View("АктПриемкиL", new string[] {
            "ДатаПриемки as \'Дата приемки\'",
            "НомерАкта as \'Номер акта\'",
            "ФИО as \'ФИО\'",
            "Должность as \'Должность\'",
            "НомерТН as \'Номер ТН\'",
            "Поставщик as \'Поставщик\'",
            "НомерПозиции as \'Номер позиции\'",
            "Материал as \'Материал\'",
            "Колво as \'Колво\'"})]
    public class АктПриемки : ICSSoft.STORMNET.DataObject
    {
        
        private string fДатаПриемки;
        
        private int fНомерАкта;
        
        private string fФИО;
        
        private string fДолжность;
        
        private string fПоставщик;
        
        private int fНомерПозиции;
        
        private string fМатериал;
        
        private int fКолво;
        
        private int fНомерТН;
        
        // *** Start programmer edit section *** (АктПриемки CustomMembers)

        // *** End programmer edit section *** (АктПриемки CustomMembers)

        
        /// <summary>
        /// ДатаПриемки.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.ДатаПриемки CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.ДатаПриемки CustomAttributes)
        [StrLen(255)]
        public virtual string ДатаПриемки
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.ДатаПриемки Get start)

                // *** End programmer edit section *** (АктПриемки.ДатаПриемки Get start)
                string result = this.fДатаПриемки;
                // *** Start programmer edit section *** (АктПриемки.ДатаПриемки Get end)

                // *** End programmer edit section *** (АктПриемки.ДатаПриемки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.ДатаПриемки Set start)

                // *** End programmer edit section *** (АктПриемки.ДатаПриемки Set start)
                this.fДатаПриемки = value;
                // *** Start programmer edit section *** (АктПриемки.ДатаПриемки Set end)

                // *** End programmer edit section *** (АктПриемки.ДатаПриемки Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.Должность CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.Должность Get start)

                // *** End programmer edit section *** (АктПриемки.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (АктПриемки.Должность Get end)

                // *** End programmer edit section *** (АктПриемки.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.Должность Set start)

                // *** End programmer edit section *** (АктПриемки.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (АктПриемки.Должность Set end)

                // *** End programmer edit section *** (АктПриемки.Должность Set end)
            }
        }
        
        /// <summary>
        /// Колво.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.Колво CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.Колво CustomAttributes)
        public virtual int Колво
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.Колво Get start)

                // *** End programmer edit section *** (АктПриемки.Колво Get start)
                int result = this.fКолво;
                // *** Start programmer edit section *** (АктПриемки.Колво Get end)

                // *** End programmer edit section *** (АктПриемки.Колво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.Колво Set start)

                // *** End programmer edit section *** (АктПриемки.Колво Set start)
                this.fКолво = value;
                // *** Start programmer edit section *** (АктПриемки.Колво Set end)

                // *** End programmer edit section *** (АктПриемки.Колво Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.Материал CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.Материал CustomAttributes)
        [StrLen(255)]
        public virtual string Материал
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.Материал Get start)

                // *** End programmer edit section *** (АктПриемки.Материал Get start)
                string result = this.fМатериал;
                // *** Start programmer edit section *** (АктПриемки.Материал Get end)

                // *** End programmer edit section *** (АктПриемки.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.Материал Set start)

                // *** End programmer edit section *** (АктПриемки.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (АктПриемки.Материал Set end)

                // *** End programmer edit section *** (АктПриемки.Материал Set end)
            }
        }
        
        /// <summary>
        /// НомерАкта.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.НомерАкта CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.НомерАкта CustomAttributes)
        public virtual int НомерАкта
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.НомерАкта Get start)

                // *** End programmer edit section *** (АктПриемки.НомерАкта Get start)
                int result = this.fНомерАкта;
                // *** Start programmer edit section *** (АктПриемки.НомерАкта Get end)

                // *** End programmer edit section *** (АктПриемки.НомерАкта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.НомерАкта Set start)

                // *** End programmer edit section *** (АктПриемки.НомерАкта Set start)
                this.fНомерАкта = value;
                // *** Start programmer edit section *** (АктПриемки.НомерАкта Set end)

                // *** End programmer edit section *** (АктПриемки.НомерАкта Set end)
            }
        }
        
        /// <summary>
        /// НомерПозиции.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.НомерПозиции CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.НомерПозиции CustomAttributes)
        public virtual int НомерПозиции
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.НомерПозиции Get start)

                // *** End programmer edit section *** (АктПриемки.НомерПозиции Get start)
                int result = this.fНомерПозиции;
                // *** Start programmer edit section *** (АктПриемки.НомерПозиции Get end)

                // *** End programmer edit section *** (АктПриемки.НомерПозиции Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.НомерПозиции Set start)

                // *** End programmer edit section *** (АктПриемки.НомерПозиции Set start)
                this.fНомерПозиции = value;
                // *** Start programmer edit section *** (АктПриемки.НомерПозиции Set end)

                // *** End programmer edit section *** (АктПриемки.НомерПозиции Set end)
            }
        }
        
        /// <summary>
        /// НомерТН.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.НомерТН CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.НомерТН CustomAttributes)
        public virtual int НомерТН
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.НомерТН Get start)

                // *** End programmer edit section *** (АктПриемки.НомерТН Get start)
                int result = this.fНомерТН;
                // *** Start programmer edit section *** (АктПриемки.НомерТН Get end)

                // *** End programmer edit section *** (АктПриемки.НомерТН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.НомерТН Set start)

                // *** End programmer edit section *** (АктПриемки.НомерТН Set start)
                this.fНомерТН = value;
                // *** Start programmer edit section *** (АктПриемки.НомерТН Set end)

                // *** End programmer edit section *** (АктПриемки.НомерТН Set end)
            }
        }
        
        /// <summary>
        /// Поставщик.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.Поставщик CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.Поставщик CustomAttributes)
        [StrLen(255)]
        public virtual string Поставщик
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.Поставщик Get start)

                // *** End programmer edit section *** (АктПриемки.Поставщик Get start)
                string result = this.fПоставщик;
                // *** Start programmer edit section *** (АктПриемки.Поставщик Get end)

                // *** End programmer edit section *** (АктПриемки.Поставщик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.Поставщик Set start)

                // *** End programmer edit section *** (АктПриемки.Поставщик Set start)
                this.fПоставщик = value;
                // *** Start programmer edit section *** (АктПриемки.Поставщик Set end)

                // *** End programmer edit section *** (АктПриемки.Поставщик Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (АктПриемки.ФИО CustomAttributes)

        // *** End programmer edit section *** (АктПриемки.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (АктПриемки.ФИО Get start)

                // *** End programmer edit section *** (АктПриемки.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (АктПриемки.ФИО Get end)

                // *** End programmer edit section *** (АктПриемки.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПриемки.ФИО Set start)

                // *** End programmer edit section *** (АктПриемки.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (АктПриемки.ФИО Set end)

                // *** End programmer edit section *** (АктПриемки.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АктПриемкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АктПриемкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АктПриемкиE", typeof(IIS.Roop.АктПриемки));
                }
            }
            
            /// <summary>
            /// "АктПриемкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АктПриемкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АктПриемкиL", typeof(IIS.Roop.АктПриемки));
                }
            }
        }
    }
}
