//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Roop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отпуск материала.
    /// </summary>
    // *** Start programmer edit section *** (ОтпускМатериала CustomAttributes)

    // *** End programmer edit section *** (ОтпускМатериала CustomAttributes)
    [AutoAltered()]
    [Caption("Отпуск материала")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтпускМатериалаE", new string[] {
            "ДатаПроводки as \'Дата проводки\'",
            "НомерЗаказа as \'Номер заказа\'",
            "ФИОЗаказчика as \'Ф и о заказчика\'",
            "АдресЗаказа as \'Адрес заказа\'",
            "СпособДоставки as \'Способ доставки\'"})]
    [View("ОтпускМатериалаL", new string[] {
            "ДатаПроводки as \'Дата проводки\'",
            "НомерЗаказа as \'Номер заказа\'",
            "ФИОЗаказчика as \'Ф и о заказчика\'",
            "АдресЗаказа as \'Адрес заказа\'",
            "СпособДоставки as \'Способ доставки\'"})]
    public class ОтпускМатериала : ICSSoft.STORMNET.DataObject
    {
        
        private int fДатаПроводки;
        
        private string fФИОЗаказчика;
        
        private string fАдресЗаказа;
        
        private string fСпособДоставки;
        
        private int fНомерЗаказа;
        
        // *** Start programmer edit section *** (ОтпускМатериала CustomMembers)

        // *** End programmer edit section *** (ОтпускМатериала CustomMembers)

        
        /// <summary>
        /// АдресЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.АдресЗаказа CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.АдресЗаказа CustomAttributes)
        [StrLen(255)]
        public virtual string АдресЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.АдресЗаказа Get start)

                // *** End programmer edit section *** (ОтпускМатериала.АдресЗаказа Get start)
                string result = this.fАдресЗаказа;
                // *** Start programmer edit section *** (ОтпускМатериала.АдресЗаказа Get end)

                // *** End programmer edit section *** (ОтпускМатериала.АдресЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.АдресЗаказа Set start)

                // *** End programmer edit section *** (ОтпускМатериала.АдресЗаказа Set start)
                this.fАдресЗаказа = value;
                // *** Start programmer edit section *** (ОтпускМатериала.АдресЗаказа Set end)

                // *** End programmer edit section *** (ОтпускМатериала.АдресЗаказа Set end)
            }
        }
        
        /// <summary>
        /// ДатаПроводки.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки CustomAttributes)
        public virtual int ДатаПроводки
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки Get start)

                // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки Get start)
                int result = this.fДатаПроводки;
                // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки Get end)

                // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки Set start)

                // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки Set start)
                this.fДатаПроводки = value;
                // *** Start programmer edit section *** (ОтпускМатериала.ДатаПроводки Set end)

                // *** End programmer edit section *** (ОтпускМатериала.ДатаПроводки Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.НомерЗаказа CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.НомерЗаказа CustomAttributes)
        public virtual int НомерЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.НомерЗаказа Get start)

                // *** End programmer edit section *** (ОтпускМатериала.НомерЗаказа Get start)
                int result = this.fНомерЗаказа;
                // *** Start programmer edit section *** (ОтпускМатериала.НомерЗаказа Get end)

                // *** End programmer edit section *** (ОтпускМатериала.НомерЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.НомерЗаказа Set start)

                // *** End programmer edit section *** (ОтпускМатериала.НомерЗаказа Set start)
                this.fНомерЗаказа = value;
                // *** Start programmer edit section *** (ОтпускМатериала.НомерЗаказа Set end)

                // *** End programmer edit section *** (ОтпускМатериала.НомерЗаказа Set end)
            }
        }
        
        /// <summary>
        /// СпособДоставки.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.СпособДоставки CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.СпособДоставки CustomAttributes)
        [StrLen(255)]
        public virtual string СпособДоставки
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.СпособДоставки Get start)

                // *** End programmer edit section *** (ОтпускМатериала.СпособДоставки Get start)
                string result = this.fСпособДоставки;
                // *** Start programmer edit section *** (ОтпускМатериала.СпособДоставки Get end)

                // *** End programmer edit section *** (ОтпускМатериала.СпособДоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.СпособДоставки Set start)

                // *** End programmer edit section *** (ОтпускМатериала.СпособДоставки Set start)
                this.fСпособДоставки = value;
                // *** Start programmer edit section *** (ОтпускМатериала.СпособДоставки Set end)

                // *** End programmer edit section *** (ОтпускМатериала.СпособДоставки Set end)
            }
        }
        
        /// <summary>
        /// ФИОЗаказчика.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМатериала.ФИОЗаказчика CustomAttributes)

        // *** End programmer edit section *** (ОтпускМатериала.ФИОЗаказчика CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОЗаказчика
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМатериала.ФИОЗаказчика Get start)

                // *** End programmer edit section *** (ОтпускМатериала.ФИОЗаказчика Get start)
                string result = this.fФИОЗаказчика;
                // *** Start programmer edit section *** (ОтпускМатериала.ФИОЗаказчика Get end)

                // *** End programmer edit section *** (ОтпускМатериала.ФИОЗаказчика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМатериала.ФИОЗаказчика Set start)

                // *** End programmer edit section *** (ОтпускМатериала.ФИОЗаказчика Set start)
                this.fФИОЗаказчика = value;
                // *** Start programmer edit section *** (ОтпускМатериала.ФИОЗаказчика Set end)

                // *** End programmer edit section *** (ОтпускМатериала.ФИОЗаказчика Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтпускМатериалаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускМатериалаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускМатериалаE", typeof(IIS.Roop.ОтпускМатериала));
                }
            }
            
            /// <summary>
            /// "ОтпускМатериалаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускМатериалаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускМатериалаL", typeof(IIS.Roop.ОтпускМатериала));
                }
            }
        }
    }
}
