//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Roop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч акта приемки.
    /// </summary>
    // *** Start programmer edit section *** (ТЧАктаПриемки CustomAttributes)

    // *** End programmer edit section *** (ТЧАктаПриемки CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч акта приемки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧАктаПриемкиE", new string[] {
            "НомерПозиции as \'Номер позиции\'",
            "Материал as \'Материал\'",
            "Колво as \'Колво\'",
            "ИмяСклада as \'Имя склада\'"})]
    [View("ТЧАктаПриемкиL", new string[] {
            "НомерПозиции as \'Номер позиции\'",
            "Материал as \'Материал\'",
            "Колво as \'Колво\'",
            "ИмяСклада as \'Имя склада\'"})]
    public class ТЧАктаПриемки : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПозиции;
        
        private string fМатериал;
        
        private int fКолво;
        
        private string fИмяСклада;
        
        // *** Start programmer edit section *** (ТЧАктаПриемки CustomMembers)

        // *** End programmer edit section *** (ТЧАктаПриемки CustomMembers)

        
        /// <summary>
        /// ИмяСклада.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.ИмяСклада CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.ИмяСклада CustomAttributes)
        [StrLen(255)]
        public virtual string ИмяСклада
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.ИмяСклада Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.ИмяСклада Get start)
                string result = this.fИмяСклада;
                // *** Start programmer edit section *** (ТЧАктаПриемки.ИмяСклада Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.ИмяСклада Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.ИмяСклада Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.ИмяСклада Set start)
                this.fИмяСклада = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.ИмяСклада Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.ИмяСклада Set end)
            }
        }
        
        /// <summary>
        /// Колво.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.Колво CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.Колво CustomAttributes)
        public virtual int Колво
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Колво Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Колво Get start)
                int result = this.fКолво;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Колво Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Колво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Колво Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Колво Set start)
                this.fКолво = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Колво Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Колво Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.Материал CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.Материал CustomAttributes)
        [StrLen(255)]
        public virtual string Материал
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Материал Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Материал Get start)
                string result = this.fМатериал;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Материал Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Материал Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Материал Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Материал Set end)
            }
        }
        
        /// <summary>
        /// НомерПозиции.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции CustomAttributes)
        public virtual int НомерПозиции
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции Get start)
                int result = this.fНомерПозиции;
                // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции Set start)
                this.fНомерПозиции = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧАктаПриемкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧАктаПриемкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧАктаПриемкиE", typeof(IIS.Roop.ТЧАктаПриемки));
                }
            }
            
            /// <summary>
            /// "ТЧАктаПриемкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧАктаПриемкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧАктаПриемкиL", typeof(IIS.Roop.ТЧАктаПриемки));
                }
            }
        }
    }
}
